### ISSUE TITLE
what next

### ISSUE THREAD

**Issue by milianmalfait05** [dev6920/fortnite-accountID-grabber#1]
Hello,
What can you do with someone's epicgames ID?
How do you pull an account with the account ID?

**Comment by Velislaver** [comment]
It dont give me account id for any reason

**Comment by dev6920** [comment]
it might be getting rate limiting 

heres a another way to get id 

https://fortnitetracker.com/profile/all/{username}/events
                                                             ^^^^^^
replace with username

example :
https://fortnitetracker.com/profile/all/dev/events

next view-source (ctrl u)

next do (ctrl f)

search "accountid"

should see something like this 
playerInfo":{"accountId":"f813696d-d25c-4ab1-ae2d-b53b1bb01411","playerName":"Dev","displayName":"Dev","platformSlug":"epic","isPremium":false,

**Comment by Velislaver** [comment]
Can i crack account with this account id

**Comment by asim634364564564565464646** [comment]
how do i do it and where do i tupe the code in
