### ISSUE TITLE
I want to pull this acc please 

### ISSUE THREAD

**Issue by chase400** [dev6920/fortnite-accountID-grabber#4]
The display of it is CanUNotXD and pull request i don't understand how to use

**Comment by MysticThretz** [comment]
This is a random user did you ever figure out how to get the account.

**Comment by chase400** [comment]
No

**Comment by Jooz-is-papi** [comment]
I have a account I need pulled

**Comment by iliketopullids** [comment]
Vrtuality

**Comment by iliketopullids** [comment]
Yo i need a account id

**Comment by iliketopullids** [comment]
Yo i need a account id pulled this is thr display username 
Vrtuality
